"""Tests for Phase 9a: knarr-mail skill handler and storage."""
import asyncio
import json
import time
import uuid

import pytest

from knarr.dht.storage import Storage
from knarr.mail.handler import (
    handle,
    set_node,
    _mail_config,
    MAX_TTL_HOURS,
    DEFAULT_TTL_HOURS,
    MAX_ACK_BATCH,
)


class FakeNodeInfo:
    def __init__(self, node_id):
        self.node_id = node_id


class FakeNode:
    """Minimal node mock for mail handler tests."""

    def __init__(self, node_id="local_node_id_abc123", config=None):
        self.node_info = FakeNodeInfo(node_id)
        self.storage = Storage(":memory:")
        self._config = config or {"mail": {}}


@pytest.fixture
def node():
    n = FakeNode()
    set_node(n)
    return n


@pytest.fixture
def remote_node_id():
    return "remote_node_id_def456"


def _send(node, from_id, body=None, ttl_hours=72, **kwargs):
    """Helper to call send action."""
    if body is None:
        body = {"type": "text", "content": "hello"}
    input_data = {
        "action": "send",
        "body": body,
        "ttl_hours": ttl_hours,
        "_caller_node_id": from_id,
    }
    input_data.update(kwargs)
    return asyncio.run(handle(input_data))


def _poll(node, since=None, filters=None, limit=50):
    """Helper to call poll action (local)."""
    input_data = {
        "action": "poll",
        "_caller_node_id": node.node_info.node_id,
    }
    if since is not None:
        input_data["since"] = since
    if filters:
        input_data["filters"] = filters
    if limit != 50:
        input_data["limit"] = limit
    return asyncio.run(handle(input_data))


def _ack(node, message_ids, disposition="read"):
    """Helper to call ack action (local)."""
    return asyncio.run(handle({
        "action": "ack",
        "message_ids": message_ids,
        "disposition": disposition,
        "_caller_node_id": node.node_info.node_id,
    }))


# -- Basic send/poll/ack --

def test_mail_send_and_poll(node, remote_node_id):
    """Send a message, poll returns it with correct fields."""
    result = _send(node, remote_node_id, body={"type": "text", "content": "hello agent"})
    assert result["status"] == "delivered"
    assert "message_id" in result
    assert "timestamp" in result

    poll = _poll(node)
    assert len(poll["messages"]) == 1
    msg = poll["messages"][0]
    assert msg["message_id"] == result["message_id"]
    assert msg["from_node"] == remote_node_id
    assert msg["body"]["content"] == "hello agent"
    assert msg["status"] == "unread"


def test_mail_server_assigned_id(node, remote_node_id):
    """message_id is generated by recipient, not sender."""
    r1 = _send(node, remote_node_id)
    r2 = _send(node, remote_node_id)
    assert r1["message_id"] != r2["message_id"]
    # Both are valid UUIDs
    uuid.UUID(r1["message_id"])
    uuid.UUID(r2["message_id"])


def test_mail_cursor_pagination(node, remote_node_id):
    """since token returns only newer messages."""
    r1 = _send(node, remote_node_id, body={"type": "text", "content": "msg1"})
    r2 = _send(node, remote_node_id, body={"type": "text", "content": "msg2"})
    r3 = _send(node, remote_node_id, body={"type": "text", "content": "msg3"})

    # Poll all
    poll1 = _poll(node)
    assert len(poll1["messages"]) == 3
    assert poll1["next_token"] is not None

    # Poll with cursor — should get nothing (all returned)
    poll2 = _poll(node, since=poll1["next_token"])
    assert len(poll2["messages"]) == 0

    # Send another and poll from cursor
    r4 = _send(node, remote_node_id, body={"type": "text", "content": "msg4"})
    poll3 = _poll(node, since=poll1["next_token"])
    assert len(poll3["messages"]) == 1
    assert poll3["messages"][0]["body"]["content"] == "msg4"


def test_mail_ack_read(node, remote_node_id):
    """Ack marks as read, excluded from default poll."""
    r = _send(node, remote_node_id)
    ack = _ack(node, [r["message_id"]], "read")
    assert ack["acknowledged"] == 1

    # Default poll (unread only) — should be empty
    poll = _poll(node)
    assert len(poll["messages"]) == 0

    # Poll with status=read should find it
    poll2 = _poll(node, filters={"status": "read"})
    assert len(poll2["messages"]) == 1


def test_mail_ack_delete(node, remote_node_id):
    """Ack with deleted disposition hard-deletes."""
    r = _send(node, remote_node_id)
    ack = _ack(node, [r["message_id"]], "deleted")
    assert ack["acknowledged"] == 1

    # Gone from all statuses
    poll = _poll(node, filters={"status": "read"})
    assert len(poll["messages"]) == 0
    poll2 = _poll(node, filters={"status": "unread"})
    assert len(poll2["messages"]) == 0


def test_mail_ack_archived(node, remote_node_id):
    """Ack with archived sets status to archived."""
    r = _send(node, remote_node_id)
    _ack(node, [r["message_id"]], "archived")

    poll = _poll(node, filters={"status": "archived"})
    assert len(poll["messages"]) == 1


# -- TTL --

def test_mail_ttl_expiry(node, remote_node_id):
    """SENTINEL: Expired messages are purged by cleanup."""
    # Send with 0.001 hour TTL (3.6 seconds)
    _send(node, remote_node_id, ttl_hours=0.001)

    # Immediately visible
    poll1 = _poll(node)
    assert len(poll1["messages"]) == 1

    # Simulate time passing — purge
    node.storage.purge_expired_mail(time.time() + 10)

    # Now gone
    poll2 = _poll(node)
    assert len(poll2["messages"]) == 0


# -- Local-only enforcement --

def test_mail_poll_local_only(node, remote_node_id):
    """SENTINEL: Remote caller cannot poll another node's mailbox."""
    _send(node, remote_node_id)

    result = asyncio.run(handle({
        "action": "poll",
        "_caller_node_id": remote_node_id,  # NOT the local node
    }))
    assert result.get("error") == "local_only"


def test_mail_ack_local_only(node, remote_node_id):
    """Remote caller cannot ack another node's messages."""
    r = _send(node, remote_node_id)

    result = asyncio.run(handle({
        "action": "ack",
        "message_ids": [r["message_id"]],
        "disposition": "read",
        "_caller_node_id": remote_node_id,
    }))
    assert result.get("error") == "local_only"


# -- Mailbox policy --

def test_mail_accept_whitelist(remote_node_id):
    """Whitelist mode rejects non-whitelisted senders."""
    n = FakeNode(config={"mail": {"accept_from": "whitelist", "whitelist": ["allowed_node"]}})
    set_node(n)

    result = _send(n, remote_node_id)
    assert result["status"] == "rejected"
    assert result["reason"] == "not_whitelisted"

    # Allowed node can send
    result2 = _send(n, "allowed_node")
    assert result2["status"] == "delivered"


def test_mail_accept_none():
    """Disabled mailbox rejects all messages."""
    n = FakeNode(config={"mail": {"accept_from": "none"}})
    set_node(n)

    result = _send(n, "anyone")
    assert result["status"] == "rejected"
    assert result["reason"] == "mailbox_disabled"


def test_mail_max_messages(node, remote_node_id):
    """Rejects when mailbox is full."""
    # Set low limit
    node._config["mail"]["max_messages"] = 3
    set_node(node)

    for i in range(3):
        r = _send(node, remote_node_id, body={"type": "text", "content": f"msg{i}"})
        assert r["status"] == "delivered"

    r = _send(node, remote_node_id, body={"type": "text", "content": "overflow"})
    assert r["status"] == "rejected"
    assert r["reason"] == "mailbox_full"


# -- Filters --

def test_mail_session_filter(node, remote_node_id):
    """Poll with session_id filter returns correct messages."""
    _send(node, remote_node_id, body={"type": "text", "content": "a", "session_id": "sess-1"})
    _send(node, remote_node_id, body={"type": "text", "content": "b", "session_id": "sess-2"})
    _send(node, remote_node_id, body={"type": "text", "content": "c", "session_id": "sess-1"})

    poll = _poll(node, filters={"session_id": "sess-1"})
    assert len(poll["messages"]) == 2
    for m in poll["messages"]:
        assert m["body"]["session_id"] == "sess-1"


def test_mail_type_filter(node, remote_node_id):
    """Poll with type filter returns correct messages."""
    _send(node, remote_node_id, body={"type": "text", "content": "a"})
    _send(node, remote_node_id, body={"type": "offer", "content": "b"})
    _send(node, remote_node_id, body={"type": "text", "content": "c"})

    poll = _poll(node, filters={"type": "offer"})
    assert len(poll["messages"]) == 1
    assert poll["messages"][0]["body"]["type"] == "offer"


def test_mail_from_filter(node):
    """Poll with from filter returns messages from specific sender."""
    _send(node, "node_a", body={"type": "text", "content": "from a"})
    _send(node, "node_b", body={"type": "text", "content": "from b"})
    _send(node, "node_a", body={"type": "text", "content": "from a again"})

    poll = _poll(node, filters={"from": "node_a"})
    assert len(poll["messages"]) == 2


# -- Stale token gap --

def test_mail_stale_token_gap(node, remote_node_id):
    """Stale since token returns gap flag."""
    r1 = _send(node, remote_node_id, body={"type": "text", "content": "msg1"})

    # Get the rowid of msg1
    poll1 = _poll(node)
    token = poll1["next_token"]

    # Delete msg1 (simulating TTL purge)
    _ack(node, [r1["message_id"]], "deleted")

    # Send a new message
    _send(node, remote_node_id, body={"type": "text", "content": "msg2"})

    # Poll with stale token — should indicate gap
    poll2 = _poll(node, since=token)
    assert poll2["gap"] is True
    assert len(poll2["messages"]) == 1


# -- Edge cases --

def test_mail_unknown_action(node):
    """Unknown action returns error."""
    result = asyncio.run(handle({
        "action": "subscribe",
        "_caller_node_id": node.node_info.node_id,
    }))
    assert "error" in result


def test_mail_invalid_body(node, remote_node_id):
    """Non-dict body rejected."""
    result = asyncio.run(handle({
        "action": "send",
        "body": "not a dict",
        "_caller_node_id": remote_node_id,
    }))
    assert result.get("error") == "invalid_body"


def test_mail_total_unread(node, remote_node_id):
    """Poll response includes total_unread count."""
    _send(node, remote_node_id)
    _send(node, remote_node_id)
    _send(node, remote_node_id)

    poll = _poll(node, limit=1)
    assert poll["total_unread"] == 3
    assert len(poll["messages"]) == 1


def test_mail_ack_batch_limit(node, remote_node_id):
    """Ack with too many IDs returns error."""
    ids = [str(uuid.uuid4()) for _ in range(MAX_ACK_BATCH + 1)]
    result = _ack(node, ids)
    assert result.get("error") == "invalid_input"


def test_mail_invalid_disposition(node, remote_node_id):
    """Invalid disposition returns error."""
    r = _send(node, remote_node_id)
    result = asyncio.run(handle({
        "action": "ack",
        "message_ids": [r["message_id"]],
        "disposition": "burned",
        "_caller_node_id": node.node_info.node_id,
    }))
    assert result.get("error") == "invalid_disposition"


# -- Storage methods --

def test_storage_mail_count():
    """count_mail and count_mail_unread work correctly."""
    s = Storage(":memory:")
    assert s.count_mail() == 0

    s.store_mail("id1", "from", "to", time.time(), "{}", None, "text", None, time.time() + 3600)
    s.store_mail("id2", "from", "to", time.time(), "{}", None, "text", None, time.time() + 3600)
    assert s.count_mail() == 2
    assert s.count_mail_unread("to") == 2

    s.ack_mail(["id1"], "to", "read")
    assert s.count_mail_unread("to") == 1
    s.close()


def test_storage_purge_expired_mail():
    """purge_expired_mail deletes only expired messages."""
    s = Storage(":memory:")
    now = time.time()
    s.store_mail("exp1", "from", "to", now, "{}", None, "text", None, now - 1)  # expired
    s.store_mail("alive1", "from", "to", now, "{}", None, "text", None, now + 3600)  # alive

    purged = s.purge_expired_mail(now)
    assert purged == 1
    assert s.count_mail() == 1
    s.close()


def test_storage_cross_thread_access():
    """SENTINEL: Storage must be accessible from non-main threads (SA-9a-001)."""
    import threading
    s = Storage(":memory:")
    now = time.time()
    errors = []

    def write_from_thread():
        try:
            s.store_mail("t1", "from", "to", now, "{}", None, "text", None, now + 3600)
        except Exception as e:
            errors.append(e)

    t = threading.Thread(target=write_from_thread)
    t.start()
    t.join()
    assert not errors, f"Cross-thread storage access failed: {errors[0]}"
    assert s.count_mail() == 1
    s.close()
